version: "3.8"
services:
    node-cli:
        build:
          context: docker
          dockerfile: node/Dockerfile
        volumes:
          - ./:/next-start
    nginx-frontend:
        build:
          context: docker
          dockerfile: nginx-frontend/Dockerfile
        ports:
           - "80:80"
        depends_on:
           - frontend-node
    frontend-node:
        build:
          context: docker
          dockerfile: node/Dockerfile
        environment:
          NODE_ENV: development
        volumes:
          - ./:/next-start
        command: npm run dev
        tty: true